apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-argocd-application
  namespace: argocd
spec:
  project: default
  source:
    path: dev
    repoURL: https://github.com/sbahari/simple-argocd.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true

  
