apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
spec:
  selector:
    matchLabels:
      app: go-web-app
  replicas: 3
  template:
    metadata:
      labels:
        app: go-web-app
    spec:
      containers:
      - name: go-web-app
        image: sbahari1090/go-web-app:latest
        ports:
        - containerPort: 30000