---
apiVersion: v1
kind: Service
metadata:
  name: go-web
  labels:
    app.kubernetes.io/name: go-web
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: go-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web
  labels:
    app.kubernetes.io/name: go-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: go-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-web
    spec:  
      containers:
      - name: go-web
        image: "go-web:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: tcp
          protocol: TCP
