apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web
  namespace: argocd
spec:
  destination:
    namespace: develop
    server: https://kubernetes.default.svc
  project: coba-develop
  source:
    path: overlays/develop/web
    repoURL: https://github.com/sbahari/simple-argocd.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true